#!/bin/sh

# Check if git-lfs is installed
if ! command -v git-lfs >/dev/null 2>&1; then
  echo >&2 "\nThis repository is configured to use Git LFS, but 'git-lfs' was not found in your PATH."
  echo >&2 "If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-checkout'.\n"
  exit 2
fi

# Call the Git LFS post-checkout command with the passed arguments
git lfs post-checkout "$@"
